[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[profile.release]
lto = true

[dependencies]
axum = "0.7.4"
serde = { version = "1.0.196", features = ["derive"] }
tokio = { version = "1.35.1", features = ["full"] }
tower-http = { version = "0.5.1", features = ["cors"] }
