build-image:
	podman build . -t europe-west4-docker.pkg.dev/rw-dev-tf/extendle/backend

push-image: build-image
	podman push europe-west4-docker.pkg.dev/rw-dev-tf/extendle/backend

deploy-image: push-image
	gcloud run deploy extendle-backend \
		--image=europe-west4-docker.pkg.dev/rw-dev-tf/extendle/backend:latest \
		--region=europe-west4 \
		--project=rw-dev-tf
	# gcloud run services update-traffic extendle-backend --to-latest --region=europe-west4
